site_name: BoK
site_description: Book of Knownledge
#site_url:
#edit_uri:
theme:
  name: material
  palette:
    scheme: slate
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - annonce.dismiss
    #- content.action.edit
    - content.code.copy
    - navigation.top
    - navigation.indexes
    - navigation.footer
    #- navigation.path
    - search.suggest
    #- search.highlight
highlightjs: true
icon:
  repo: fontawesome/brands/git-alt
plugins:
  - search
  - link-marker # external
  - ezlinks # [[]]
extra:
  generator: false
